apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: %%NAMESPACE%%
  labels:
    app.kubernetes.io/name: api
  annotations:
    # AWS Network Load Balancer (layer 4)
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
